[package]
name = "flow-testkit"
description = "Integration test support for Embrasure Flow"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
flow-model.workspace = true
flow-coordinator.workspace = true
flow-ingress-journal.workspace = true
flow-state-store.workspace = true
flow-materializer.workspace = true
flow-iceberg-ext.workspace = true
iceberg.workspace = true
async-trait.workspace = true
bincode.workspace = true
anyhow.workspace = true
futures.workspace = true
tempfile.workspace = true

[lints]
workspace = true

[dev-dependencies]
parquet.workspace = true
reqsign-core = "=3.3.1"
bytes.workspace = true
typetag = "0.2"
flow-pg-source.workspace = true
flow-compactor.workspace = true
tokio.workspace = true
serde_json.workspace = true
clap.workspace = true
serde.workspace = true
toml.workspace = true
uuid.workspace = true
iceberg-catalog-rest.workspace = true
iceberg-storage-opendal = { version = "=0.10.1", default-features = false, features = ["opendal-fs", "opendal-s3"] }
